# Generated by Django 3.0.4 on 2020-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_classassignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20)),
                ('category_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'class_categories',
                'order_with_respect_to': 'class_id',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=25)),
                ('category_description', models.CharField(max_length=150, null=True)),
                ('category_weight', models.DecimalField(decimal_places=3, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'categories',
                'order_with_respect_to': 'category_id',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=20)),
                ('assignment_name', models.CharField(max_length=80)),
                ('assignment_description', models.CharField(max_length=150, null=True)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'assignments',
                'order_with_respect_to': 'assignment_id',
            },
        ),
    ]
