# Generated by Django 3.0.4 on 2020-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_assignment_category_classcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='weighted',
            field=models.BooleanField(default=False),
        ),
    ]
