# Generated by Django 3.0.4 on 2020-04-16 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200416_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment.html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e8f8f66-1191-4704-abff-f3f9314fc1fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36945686-0a5e-4541-bcb6-2431149c4304'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
