# Generated by Django 3.0.6 on 2020-05-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='est_completion_time_min',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
