# Generated by Django 3.0.4 on 2020-04-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_class_weighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
