# Generated by Django 3.0.4 on 2020-04-14 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200414_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
