# Generated by Django 3.0.6 on 2020-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200519_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
