# Generated by Django 3.0.4 on 2020-04-14 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200414_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c2b4d98-be0a-4905-bbda-fee928749ff7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
