# Generated by Django 3.0.6 on 2020-05-23 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200520_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDiscussions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=36)),
                ('discussion_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_head', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=200)),
                ('attached_media', models.FileField(null=True, upload_to='')),
                ('reply_to', models.CharField(max_length=36, null=True)),
            ],
            options={
                'db_table': 'discussions',
            },
        ),
    ]
