# Generated by Django 3.0.4 on 2020-04-14 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200414_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f66f391-93d8-45c1-9457-50e419ad068d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='classassignments',
            name='assignment_id',
            field=models.CharField(max_length=100),
        ),
    ]
