# Generated by Django 3.0.6 on 2020-05-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_classdiscussions_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
