# Generated by Django 3.0.6 on 2020-05-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20200523_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='is_head',
            new_name='is_root',
        ),
    ]
