# Generated by Django 3.0.4 on 2020-04-15 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20200414_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80539902-292d-4840-bcfd-e377e158f6d1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
