# Generated by Django 3.0.4 on 2020-04-15 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20200415_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bd0c551-cdd1-46dc-bdc0-62e48ead7d03'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
