# Generated by Django 3.0.6 on 2020-05-24 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20200523_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='attached_media',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
