# Generated by Django 3.0.6 on 2020-05-31 18:07

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20200529_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attached_media',
            field=models.FileField(null=True, upload_to=board.models.generate_assignment_media_file_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
