# Generated by Django 3.0.6 on 2020-05-31 19:03

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20200531_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attached_media',
            field=models.FileField(max_length=300, null=True, upload_to=board.models.generate_assignment_media_file_path),
        ),
    ]
