# Generated by Django 3.0.4 on 2020-04-13 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('teacher_id', models.CharField(max_length=4)),
                ('id_picture', models.ImageField(blank=True, default='id_pictures/default_pfp.png', upload_to='id_pictures')),
                ('email_address', models.CharField(max_length=320)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
                'order_with_respect_to': 'teacher_id',
            },
        ),
    ]
