# Generated by Django 3.0.4 on 2020-04-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f5d03391-5f90-4adc-b444-9c6cc3ca43a9'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id_picture', models.ImageField(blank=True, default='id_pictures/default_pfp.png', upload_to='id_pictures')),
                ('email_address', models.CharField(max_length=320)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
                'order_with_respect_to': 'last_name',
            },
        ),
    ]
