# Generated by Django 3.0.4 on 2020-04-16 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3298a64d-9d1a-437e-b7ef-dbccf4778eba'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
