# Generated by Django 3.0.6 on 2020-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200416_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pref_pronoun',
            field=models.CharField(default='Mr.', max_length=5),
        ),
    ]
