# Generated by Django 3.0.6 on 2020-05-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_pref_pronoun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='pref_pronoun',
            new_name='pref_title',
        ),
    ]
