# Generated by Django 3.0.4 on 2020-04-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1640c9f9-1cf4-4f90-9d9e-0ab406b82069'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('assignment_id', models.CharField(max_length=100)),
                ('enrollment_id', models.CharField(max_length=100)),
                ('date_submitted', models.DateTimeField(default=None, null=True)),
                ('score', models.IntegerField(default=None, null=True)),
                ('file', models.FileField(default=None, null=True, upload_to='media/submission_files')),
                ('comments', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'order_with_respect_to': 'assignment_id',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('grade', models.IntegerField(default=11)),
                ('id_picture', models.ImageField(upload_to='media/id_pictures')),
                ('email_address', models.CharField(max_length=320, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'order_with_respect_to': 'student_id',
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c5e4d290-0956-48cd-b54e-787bc1daa2e1'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_id', models.CharField(max_length=7)),
                ('class_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'class_enrollment',
                'order_with_respect_to': 'student_id',
            },
        ),
    ]
