# Generated by Django 3.0.4 on 2020-04-16 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61c7b44f-2224-4fb6-b5bf-5b965586024d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ab8f1d9-8453-43fa-86ae-4d9c39e94c37'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
