# Generated by Django 3.0.4 on 2020-04-16 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200416_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4872c0c9-900a-44bd-bc7d-0b172c1c5a2f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('084208a1-e711-4484-9f06-1842daa39426'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
