# Generated by Django 3.0.6 on 2020-05-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_submission_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
