# Generated by Django 3.0.4 on 2020-04-16 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200416_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac37b02d-f432-4237-8e3a-6065d9040a5f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6fd8c8a-d46d-45ac-a8e3-fd73160dd61f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
