# Generated by Django 3.0.4 on 2020-04-17 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200416_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7bf7ac7-316f-47e4-b220-58768c7abc96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('674bff16-2e53-440b-95c3-24bc9d03dcff'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
