# Generated by Django 3.0.6 on 2020-06-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200606_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(max_length=36)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'grade_history',
                'order_with_respect_to': 'enrollment_id',
            },
        ),
    ]
