# Generated by Django 3.0.4 on 2020-04-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_cal_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cal_credentials',
            field=models.FileField(null=True, upload_to='tokens/5171991'),
        ),
    ]
