# Generated by Django 3.0.4 on 2020-05-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200430_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cal_credentials',
            field=models.FileField(null=True, upload_to='tokens/5171991'),
        ),
    ]
