# Generated by Django 3.0.4 on 2020-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200501_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cal_event_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
